name: LootKiste
version: 0.1
author: NeoPrince
website: http://myralia.de
main: de.myralia.lootkiste.LootKiste
commands:
   item:
      description: kommandos im zusammenhang mit sonderitems
      usage: /item
      permission: akte.akte
      permission-message: keine Berechtigung